### ISSUE TITLE
¿ When the user set Dark Mode in the App as default. Should we still allow Light Theme to be set against the self-made preferences of the user ?

### ISSUE THREAD

**Issue by creyD** [Dorson/CSS-Dark-Mode-and-color-switch#1]
**Describe the bug**
In the bottom left corner the "light" theme switch doesn't work.

**To Reproduce**
1. Go to the bottom left corner
2. Click on the snowflake button

**Expected behavior**
I think it should switch the site to light mode

Great work otherwise!

**Comment by Dorson** [comment]
**Thx for the report !**

Works for me in the latest Chrome and Firefox + mobile simulators.

That snowflake button is the lazy feature without extra code, because it sets an undefined CSS class. White CSS class is not defined, because white was set as default in the CSS file. White is set in the :root CSS class, which is used as default, when other things fail.

Snow Flake works only, when other color was already set, AND when user has no Dark mode preference.

Works in Chrome and Firefox that way.

**Can solve by making an extra html.snow CSS class with white color variables, but I wanted to exploit the bug, when CSS classes are not defined.** 

**It's also a feature !** If user sets snow white as default, then no automatic dark color can be set in the night dynamically. It's like a harm prevention. Works to reset color, but does not work to set white as the strict default color.

You probably have Dark Mode browser preference by default ?

**Comment by creyD** [comment]
Yes I have and I am using the latest Chromium Edge release...

**Comment by Dorson** [comment]
This is a valid **Exception Paradox** between the past user preference for the default **and automatic** Dark Mode of the browser, and the spontaneous user intention to have the White Theme colors active for the specific web app, or for the moment in time.

_In the exception paradox,_ "every rule has an exception" that leads to a contradiction of the rule.

We solve the exception paradoxes with **compromises or exception rules.**

1. One valid compromise is to allow the user to over-write the previously made automatic dark mode setting of the app or browser.

For this we could define one global Light Color theme CSS class name, in addition to the default colors that were also white by default. Then we use this exception case CSS class to reset the Dark Mode, when and where needed. When the user did make the button click = intended action against previous preference.

```
:root , html.reset-dark {

--color-html : #F9F9F9 ;
--color-body : #fdfdfd ;
--color-text : #051105 ;
--color-link : #1122D8 ;

}
```

**Or we make specific exceptions** to the @media (prefers-color-scheme: dark)  rule itself, which deals with the paradox directly, if it ever works in the future browsers :

```
@media screen and (prefers-color-scheme: dark) not (light-level: washed)  {

 html:not(.reset-dark) {
  --color-html: #0e0b0b ;
  --color-body: #1a1414 ;
  --color-text: #d1d1d1 ;
  --color-link: #4fbcff ;
  --color-selected-text: #000 ;
  --color-selected-bg: #CF7 ;
  }
}
```

_The following_ : **exception CSS rule combos** seem to work in the test so far:

```
:root , :root.reset-dark { background:  white ; }
OR
:root , html.reset-dark { background:  white ; }
```

In the fix edit, we called it **html.snow-white** color class to make fun of the melting snow moment. It's like the momentary preferences. Changes like the melting snow with every other day :-)


 **I would reason :**

If the user wants to set the white background as an exception to the automatic Dark Mode, then we should let the user to do so for the situation and the moment in which the user wants to do so. Maybe it's extra sunny or bright in the moment.


**Opinions and solutions** to the user-selected + automatic Dark Mode exception paradox are welcome ! :+1:

**Comment by creyD** [comment]
Yeah as it is the expected behavior when clicking on a "light theme" button that the light theme is actually activated.

**Comment by Dorson** [comment]
Now fixed. Opinions and solution suggestions for this paradox are still welcome.

Exception case solutions highly welcome !

**Comment by creyD** [comment]
Looks good! :)
